### ISSUE TITLE
WscMain->write(): fflush($handle) missed

### ISSUE THREAD

**Issue by eugenchenko** [arthurkushman/php-wss#11]
First way to resolve:

```
    protected function write(string $data) : void
    {
        $written = fwrite($this->socket, $data);
        fflush($this->socket);
        if ($written < strlen($data)) {
            throw new ConnectionException(
                "Could only write $written out of " . strlen($data) . " bytes."
            );
        }
    }
```

Second way to resolve:
```
    public function flush() {
        return fflush($this->socket);
    }

```

**Comment by arthurkushman** [comment]
Here I'm just fixing other issues, don't bother yet

**Comment by eugenchenko** [comment]
The problem explained here:

https://stackoverflow.com/a/39407561

Function write NOT ALWAYS sends data. Data MAY BE stored in buffer without real sending

**Comment by arthurkushman** [comment]
Exactly, that is why fragments will be collected in buffer before send, let's assume we have a 100323 long message - the core will create the buffer ex.: up to 8096 bytes and will send messages by chunks of 8096 bytes, not `const DEFAULT_FRAGMENT_SIZE = 4096;` or whatever we use in code, if u wish to send all data at once - u can increase this value in `$this->options['fragment_size']` if for instance u need to send 7123b messages.

**Comment by arthurkushman** [comment]
Now `fragment_size` can be set as follows: 
```
$config = new ClientConfig();
$config->setFragmentSize(8096);
```
