### ISSUE TITLE
WscMain return type : void not possible for PHP 7.0

### ISSUE THREAD

**Issue by petafuel** [arthurkushman/php-wss#12]
Hey there, 

may it be possible to remove the return type : void in the WscMain.php for all the functions? This will only work with PHP 7.2 but PHP 7.0 will throw errors because this return type is not supported in this version. 

Thanks for your feedback 👍

**Comment by arthurkushman** [comment]
It was implemented since PHP7.1 
https://wiki.php.net/rfc/void_return_type

Since in composer.json PHP >=7.0 I'll fix this in near future. 
Thx.

**Comment by arthurkushman** [comment]
As mentioned here - https://seld.be/notes/php-versions-stats-2018-1-edition
there are many servers running PHP7.0 about 23% in the world.

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/php-wss/releases/tag/1.3.4
