### ISSUE TITLE
Push notifications to client

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#15]
How to push notifications from the server to the client without the client sends a message to the server first?

At a given point something happens on the server and the server needs to push the notification to the client?

Where can I put logic that check for updates in the database?

It doesn't seem to be possible.. As I see it the server can only reply on a messages from the client...?

**Comment by clarkk** [comment]
And possibility to set a sleep/delay on each loop where you put the logic so it won't check the database 10 times per sec :)

**Comment by arthurkushman** [comment]
The best place to put logic of sending to client before client was sent any message is in `onOpen` method in your back-end ServerHandler implementation (because client must connect to WebSocket server anyway).
As what about `possibility to set a sleep/delay`, u can implement pre-processing logic in your application, e.g. by setting `timestamp` variable/property and check whether it`s been lapsed or not.

**Comment by arthurkushman** [comment]
Don't forget about ping/pong if that would be in demand.

**Comment by clarkk** [comment]
Another problem is to access all clients.. If you set `MAX_CLIENTS_REMAINDER_FORK` to a very low number and you connect alot of clients then you can't access `$clients` in a proper way. You will only have access to the clients that was connected at the point of working..

At the point where you fork a new process all variables and objects are copied.. So you will no longer be able to access clients from in the child from the parent and vice versa

**Comment by clarkk** [comment]
You will not be able to access og see newcoming clients/connections after the point of forking across processes

**Comment by clarkk** [comment]
https://www.ibm.com/developerworks/library/os-php-shared-memory/index.html

might be a solution

**Comment by clarkk** [comment]
This is issue is familiar with the issue you just fixed today :)

But now the problem is that the object/variable is copied

**Comment by arthurkushman** [comment]
Yes, shmops are great at using shared mem.

**Comment by arthurkushman** [comment]
To let developers use the sessions over socket client connections, I've made it possible to pass `clients_per_fork_limit` option to `WebSocketServer` class e.g.:
```
        $websocketServer = new WebSocketServer(new ServerHandler(), [
            'host'                   => '0.0.0.0',
            'port'                   => 8000,
            'clients_per_fork_limit' => 10500,
        ]);
```
Thus, u don`t need to worry about recently created connections in different processes.
In future, it would be better to add shmop functionality, to make it possible to exchange connections through shared memory, but for now this should be sufficient.

**Comment by clarkk** [comment]
And about the client push loop.. Wouldn't it be usefull with something like this
```
    public function run()
    {
        $errno = NULL;
        $errorMessage = '';

        $server = stream_socket_server("tcp://{$this->config['host']}:{$this->config['port']}", $errno, $errorMessage);
        if ($server === false) {
            die('Could not bind to socket: ' . $errno . ' - ' . $errorMessage . PHP_EOL);
        }
        
        $pid = pcntl_fork();
        
        if($pid) { // run eventLoop in parent
            @cli_set_process_title(self::PROC_TITLE);
            $this->eventLoop($server);
        }
        else{ // run push_loop in child
            @cli_set_process_title(self::PROC_TITLE);
            $this->handler->push_loop();
        }
    }
```

And then have your `push_loop` in the ServerHandler?

**Comment by clarkk** [comment]
`Right now I use redis database server to handle all connections.. Its alot faster and simple than `shmop`

https://redis.io/commands

**Comment by arthurkushman** [comment]
That`s good (I'm using redis for 6 years now), while redis is much more versatile with it's options/functions etc, shmop written in C too and integrated in php-core with api functions, there were several tests where shmop/msg functions outrun Redis in speed.

**Comment by arthurkushman** [comment]
This is definitely good idea to let users be able to send 

> And about the client push loop.. Wouldn't it be usefull with something like this
> 
>     public function run()
>     {
>         $errno = NULL;
>         $errorMessage = '';
> 
>         $server = stream_socket_server("tcp://{$this->config['host']}:{$this->config['port']}", $errno, $errorMessage);
>         if ($server === false) {
>             die('Could not bind to socket: ' . $errno . ' - ' . $errorMessage . PHP_EOL);
>         }
>         
>         $pid = pcntl_fork();
>         
>         if($pid) { // run eventLoop in parent
>             @cli_set_process_title(self::PROC_TITLE);
>             $this->eventLoop($server);
>         }
>         else{ // run push_loop in child
>             @cli_set_process_title(self::PROC_TITLE);
>             $this->handler->push_loop();
>         }
>     }
> 
> And then have your push_loop in the ServerHandler?

I've read some articles how someone use this feature in production, but this is rare high-load feature as I may noticed, so particular examples would be perfect. 

Also as a technical spec what kind of params should be provided to pushLoop method? As in other methods - `ConnectionContract`? Would it be sufficient? Why the best place to run it, is in child process - lightness? Will there be an issues with killing e.x.: `sigkill` this loop?

**Comment by clarkk** [comment]
If you really want to use multi-processing with a websocket server coded with PHP you need to setup more than one instances of PHP..

One running and handling all connections and one handling all the logic.. The instances should then could communicate via a their own socket connection (now its already complicated) where the instance handling the logic can fetch all current connections - compute som data to push, and then send back the data you need to push to each connection/client :)

**Comment by arthurkushman** [comment]
I've already used nodejs - socketio and go - gorilla/websocket, but in real life there are needs to get up and running with php, if e.g.: LNMP is the only supported.

**Comment by clarkk** [comment]
I have no earlier experience with websockets, so can't comment on that..

I have worked with both nodejs and go and IMO nodejs is faster to put some code together but it is not suitable for big projects

Go have goroutines/channels and other nice stuff but takes more time to do the same

**Comment by clarkk** [comment]
The best way to handle the PHP instances is via cronjobs.. You can setup a cronjob to execute every minute.. So if the websocket server hits the stream selection timeout it will restart shortly after.. Or if the server hits a fatal error it will restart again

And to do this I would prefer to keep the process name to `php` and not `php-wss` :) So I would prefer having to posibillity to turn off the renaming of the process :)

Then you can monitor all cron jobs in the same manner and not having different methods to keep track of each cron job..

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/php-wss/releases/tag/1.4.2
