### ISSUE TITLE
Get $this->socketConnection on Connection instance

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#16]
It would be preferred if there was a simple getter to get the private $this->socketConnection in Connection class

Then its possible to do some comparing in the ServerHandler methods

```
public function get()
{
    return $this->socketConnection;
}
```

**Comment by clarkk** [comment]
Then it is possible to get a unique ID of the socket

```
	public function onOpen(ConnectionContract $conn){
		//  Get unique ID of the socket
		$key = intval($conn->getConnection());
		
		$this->clients[$key] = $conn;
		echo 'Connection opened, total clients: ' . count($this->clients) . '('.$key.')' . "\n";
	}
```

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/php-wss/releases/tag/1.3.8
