### ISSUE TITLE
Close connection from server-side

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#20]
If you close the connection from the ServerHandler you get an error

```
	public function onMessage(ConnectionContract $conn, $msg){
		$socket_id 		= $conn->getUniqueSocketId();
		$json 			= json_decode($msg, true);
		
		if(empty($json['sid'])){
			$conn->close();
		}
	}
```

error

fwrite(): supplied resource is not a valid stream resource /var/www/.../php/class/third-party/php-wss/Components/Connection.php(41)
#0 [internal function]: {closure}(2, 'fwrite(): suppl...', '/var/www/...', 41, Array)
#1 /var/www/.../php/class/third-party/php-wss/Components/Connection.php(41): fwrite(Resource id #31, '\x81={"sid":"k0krg...')
#2 /var/www/.../php/class/Websocket.php(82): WSSC\Components\Connection->send('{"sid":"k0krggq...')
#3 /var/www/.../php/class/third-party/php-wss/WebSocketServer.php(215): ServerHandler->onMessage(Object(WSSC\Components\Connection), '{"sid":"k0krggq...')

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/php-wss/releases/tag/1.3.11
