### ISSUE TITLE
Errors as exceptions

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#21]
All errors should be thrown as exceptions

**Comment by arthurkushman** [comment]
That is why die is used when selecting:
http://php.net/manual/en/language.exceptions.php#119726

So, the code proceeds execution and there could be more complicated flows when u catching it.

**Comment by clarkk** [comment]
`die` is a equivalent to `exit` so that makes the script exit and NOT continue.. The script will not execute the destruction parts and will not close properly

It should throw an error in all cases so you will be able to handle what to do from the error thrown

**Comment by clarkk** [comment]
You should create a new exception for socket selction timeout

**Comment by clarkk** [comment]
Or even better.. Merge all your exception classes and use error codes instead
