### ISSUE TITLE
cli_set_process_title should be an option

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#23]
`cli_set_process_title` should be an option in the constructer like the other

**Comment by arthurkushman** [comment]
Why on earth process title should be an option, dependent on user? It is definitely daemon specific config to let users see what and how many they running. Tell me honestly, do u want try to set a hearts and kisses emoji there? )

**Comment by clarkk** [comment]
I run websockets as cronjobs.. If the process is renamed I can't monitor it in the same way I monitor the rest of my cronjobs..

So.. This thould be optional..

**Comment by clarkk** [comment]
Running websockets as cronjobs is the most simple way.. If a job fails it will automatically restart after 60 sec

And you can monitor everything

**Comment by clarkk** [comment]
but this won't work 100% before you fix this and the thing where you call `die` on timeouts ;)

**Comment by arthurkushman** [comment]
cli_set_process_title sets the concrete constant string === 'php-wss' process title can't be renamed, what do u need more then just killall -9 php-wss, what is the point here, am I missing something?

**Comment by clarkk** [comment]
Yes, and I don't want to rename the process name.. I want it to be `php`.. otherwise I can't monitor my cronjobs

And I run websockets as cronjobs

**Comment by clarkk** [comment]
In my project it doesn't make sense to change the processname to `php-wss`

**Comment by arthurkushman** [comment]
This project can't be developed particularly for Your monitoring tools, it is obvious that any program has it's own process name, especially daemons - do not see the point to argue here. 
Examples:
```bash
0:00.05 redis-server *:6379
0:00.00 /usr/local/opt/php71/sbin/php-fpm
```
Closing issue.

**Comment by arthurkushman** [comment]
Please, be more precise about any bug and/or further possible enhancements, as it is a drag to get all tips from every task. E.g.: this line of that class, has this behavior etc. Thx in advance.

**Comment by clarkk** [comment]
But its still not very hard to make an option `yes` / `no` if you want to rename the process to `php-wss` or not.. The default would be to rename the process
