### ISSUE TITLE
die on timeout

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#28]
Its still there?

```
if (!stream_select($readSocks, $write, $except, $this->config->getStreamSelectTimeout())) {
                die('something went wrong while selecting');
            }
```

**Comment by clarkk** [comment]
On socket timeout you want to gracefully shut down the script because you want to restart it.. This is not a fatal error (even if it was you still want to close your app or whatever in a proper manner) :)

So you don't want to shut down everything with `die` == `exit` but complete all your logic with a clean shutdown :)

**Comment by clarkk** [comment]
Someone would even choose to but you lib in a endless loop so it would restart if it hit the timeout :)

Thats not possible with `die` or `exit`

**Comment by arthurkushman** [comment]
https://github.com/arthurkushman/php-wss/releases/tag/1.3.14
