### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#29]
It must be simpler to identify errors.. Right now it is a bit complicated to handle errors

eg.
Socket timeout is not a fatal error so you need to know when this error is thrown so the application/script can be restarted

It would also be good practice to merge all exceptions to one error class and instead use error codes with a string like `SOCKET_SELECTION_TIMEOUT`.. It much easier to manage your error handling instead of long generic strings like `something went wrong bla bla bla`

It is also much more complicated to catch many different exceptions instead of just one. Then you can just fetch the error code or the error identifier like `SOCKET_SELECTION_TIMEOUT` and you know what went wrong and then you know what to do to solve the problem

**Comment by clarkk** [comment]
Right now you have
```
BadOpcodeException
BadUriException
ConnectionException
WebSocketException
```

Mergen them to one for simplicity.. And use error identifiers like `SOCKET_TIMEOUT` etc with a error code

It just too complicated to catch so many exceptions..

**Comment by arthurkushman** [comment]
`Its not a big enterpise solution :)`, no it is not - that is why there are only 4 exceptions, not 14 for ex.
The idea about err codes is practically correct (convenient) for developers.
