### ISSUE TITLE
how to send cert connect wss://

### ISSUE THREAD

**Issue by weianguo** [arthurkushman/php-wss#35]
how to send cert connect wss://
Where are the demo?

**Comment by arthurkushman** [comment]
> how to send cert connect wss://
> Where are the demo?

Where are the Demo?! Is it commercial or am I missing something? 
If u want to contribute either with any functionality or Demo - welcome )

**Comment by weianguo** [comment]
Thank you！I'm success.

`$config = new ClientConfig();
$config->setContextOptions([
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
    ],

]);
$client = new WebSocketClient('wss://127.0.0.1:13529', $config);
$client->send('{}');
$client->receive();`

**Comment by arthurkushman** [comment]
Please press a star to make the community more supportive to this project.
