### ISSUE TITLE
Getting error on setScheme() method

### ISSUE THREAD

**Issue by alissonpelizaro** [arthurkushman/php-wss#36]
Hello

I'm trying to connect but 'im getting the following error:

**Type:** TypeError
**Message:** Return value of WSSC\Components\ClientConfig::setScheme() must be an instance of WSSC\Components\void, none returned
**Filename:** /var/www/vendor/arthurkushman/php-wss/src/Components/ClientConfig.php
**Line Number:** 102

My code is only:

```
    $config = new ClientConfig();
    $config->setContextOptions([
      'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
      ]
    ]);
    $client = new WebSocketClient('wss://127.0.0.1:2021', $config);
```

Do you have idea what I'm doing wrong? I tried to solve this but without success.

**Comment by arthurkushman** [comment]
What version of php are u using?
`php -v`

**Comment by alissonpelizaro** [comment]
Hello @arthurkushman, I'm using PHP 7.0. 
I will upgrade and try again.

**Comment by arthurkushman** [comment]
Hi @alissonpelizaro please star a project it will help developing with community.
