### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by nxtimeX** [arthurkushman/php-wss#43]
hello, i have problem when i used proxy connection. can you help me?

`error_reporting(E_ALL);
ini_set('display_errors', '1');

require __DIR__ . '/vendor/autoload.php';
use WSSC\WebSocketClient;
use \WSSC\Components\ClientConfig;

$config = new ClientConfig();

$config->setProxy('24.24.25.25', '8085');
$config->setProxyAuth('MyUserName', 'MyPass');
$config->setContextOptions(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false]]);

$client = new WebSocketClient('ws://echo.websocket.org', $config);
$client->send("Hello");
echo $client->receive();`

Error Code : `Fatal error: Uncaught WSSC\Exceptions\ConnectionException: Failed to connect to the host via proxy in /var/www/html/wbSystem/vendor/arthurkushman/php-wss/src/Components/WscMain.php:151 Stack trace: #0 /var/www/html/wbSystem/vendor/arthurkushman/php-wss/src/Components/WscMain.php(65): WSSC\Components\WscMain->proxy() #1 /var/www/html/wbSystem/vendor/arthurkushman/php-wss/src/WebSocketClient.php(26): WSSC\Components\WscMain->connect() #2 /var/www/html/wbSystem/index.php(16): WSSC\WebSocketClient->__construct('ws://echo.webso...', Object(WSSC\Components\ClientConfig)) #3 {main} thrown in /var/www/html/wbSystem/vendor/arthurkushman/php-wss/src/Components/WscMain.php on line 151`

**Comment by arthurkushman** [comment]
Hi, thanks for providing the information, can u run a `telnet host port` in console to show that your host is available from that machine where u try to run the code?

**Comment by arthurkushman** [comment]
here is the patch - https://github.com/arthurkushman/php-wss/releases/tag/1.5.2

**Comment by arthurkushman** [comment]
As the problem has been solved long ago and there were no discussions under this topic I'm closing this issue.
