### ISSUE TITLE
Insufficient buffer size for HTTP collateral

### ISSUE THREAD

**Issue by truekenny** [arthurkushman/php-wss#49]
If the websocket server is behind cloudflare.com, then this may cause an error.
A couple of months ago this did not cause an error, but now the headers are over 1024 bytes.

What is the maximum size of HTTP header values?
Apache 8K
Nginx 4K-8K
IIS 8K-16K
Tomcat 8K - 48K

https://github.com/arthurkushman/php-wss/blob/adecc975a9f4da75a0abd26cf657bf2a81f075e8/src/Contracts/WscCommonsContract.php#L16

It must be increased to at least 4096.

**Comment by arthurkushman** [comment]
@truekenny thx a lot for this investigation and help.
Here is a new patch - https://github.com/arthurkushman/php-wss/releases/tag/1.6.2
