### ISSUE TITLE
Bug: unsaved large frame payload and closed connection (on server)

### ISSUE THREAD

**Issue by travisapple** [arthurkushman/php-wss#58]
Fist off, THANK YOU for making this code available. Saved me a ton of time making wss work between js and php. Trying to get wss working from js without a proxy is not a simple thing.

I **think** you have a bug in WssMain.php in decode(). You correctly state:

_"We have to check for large frames here. socket_recv cuts at 1024 bytes so if websocket-frame is > 1024 bytes we have to wait until whole data is transferd."_

However, the data from the current packet is not saved anywhere so that it can be added to the next one when it is received.

**Comment by travisapple** [comment]
Also, for larger data sizes sent from JS, larger than 64k in total with payloadLength:127, each frame can be up to 16k in FF and Chrome.

**Comment by arthurkushman** [comment]
Hi, thx for your investigation and help.
Here is fix patch: 
https://github.com/arthurkushman/php-wss/releases/tag/2.0.2

Now it should work well, before this fix server would close connection to the client, which is unacceptable.

**Comment by travisapple** [comment]
This solves the issue. Thank you for your time and, again, thank you for making this library available to us.
