### ISSUE TITLE
Connection->socketConnection changes

### ISSUE THREAD

**Issue by michalac** [arthurkushman/php-wss#6]
Hello,
in WebSocketServer you use still the same object Connection and only change his $socketConnection property. This is wrong.
In implementation example (ServerHandler) after two clients connects, property ServerHandler::clients will have two **identical** elements (because objects in PHP are passed by reference). 

Better solution is to remove Connection::getConnection method, create constructor of Connection:
` public function __construct($sockConn)
    {
        $this->socketConnection = $sockConn;
    }`

and in WebSocketServer every time to create new object Connection:
`new Connection($newClient);`
instead of
`$this->connImpl->getConnection($newClient)`

With regards
Michal

**Comment by arthurkushman** [comment]
Hi, clients will have different Resource ids:
```
-'Array\n
-(\n
-    [0] => WSSC\Components\Connection Object\n
-        (\n
-            [socketConnection:WSSC\Components\Connection:private] => Resource id #1090\n
-        )\n
-\n
-)\n
'Array\n
-(\n
-    [1] => WSSC\Components\Connection Object\n
-        (\n
-            [socketConnection:WSSC\Components\Connection:private] => Resource id #1091\n
-        )\n
-\n
-)\n
```
But the object will be the same, do u mean that there can be Race Conditions, because of single object, shared by different processes, can be changed simultaneously in one memory slot, in the heap?

**Comment by michalac** [comment]
Hello,
no, there is only single process (no forks). 

When ServerHandler::onOpen fires first time, it stores (to his ServerHandler->clients property) **reference** to Connection object (in fact WebSocketServer->connImpl). It's not clone (two independent objects), it's the same object.

Next time when you change socket resource of this object (in WebSocketServer->acceptNewClient by calling $this->connImpl->getConnection($newClient), it will changes at ServerHandler->clients[0] too (it's reference to same object).

Result from PHP 7.1.14 running at CentOS Linux, connecting two clients to websocket:

> Running WebSocketServer
Connection opend, total clients: 1
array(1) {
  [0]=>
  object(WSSC\Components\Connection)#31 (1) {
    ["socketConnection":"WSSC\Components\Connection":private]=>
    resource(109) of type (stream)
  }
}
Connection opend, total clients: 2
array(2) {
  [0]=>
  object(WSSC\Components\Connection)#31 (1) {
    ["socketConnection":"WSSC\Components\Connection":private]=>
    resource(110) of type (stream)
  }
  [1]=>
  object(WSSC\Components\Connection)#31 (1) {
    ["socketConnection":"WSSC\Components\Connection":private]=>
    resource(110) of type (stream)
  }
}
Connection closed, total clients: 1
array(1) {
  [1]=>
  object(WSSC\Components\Connection)#31 (1) {
    ["socketConnection":"WSSC\Components\Connection":private]=>
    resource(110) of type (stream)
  }
}
Connection closed, total clients: 0
array(0) {
}

Maybe you suppose two clients are serviced by separate process. But first fork occurs after 1000 clients connected concurently (can't find intention for that):
`WebSocketServer::MAX_CLIENTS_REMAINDER_FORK =1000`
and in WebSocketServer->looping:111
`if (... && $this->totalClients % self::MAX_CLIENTS_REMAINDER_FORK === 0 && ...)`
I expected every connected client will be served by separate process. First process will only accept new connections and spawns "child" process which will service just this single new connection. (Every process will have only single socket).

I think, there is another bug (maybe I'm wrong, not tested): When 1500 clients connects (there will be 2 process after fork at 1000 client), second process will share part of clients ($this->totalClients) and both process will service all 1500 clients. Baybe there is problem just in fork logic.


Btw in WebSocketServer->looping:110,119 is every time true condition:
`... && $this->totalClients !== 0 && ...`
because $this->totalClients is size of array +1 and array can't have negative size.

With regards 
Michal

**Comment by arthurkushman** [comment]
Firs of all - thank u for participation and help, sorry for delay - there are many projects at this moment.
Here is a patch which fixes this issue - https://github.com/arthurkushman/php-wss/releases/tag/1.3.6
 
Now the result of newly connected clients (collected via session etc) should be like this:
```
Running server...
new clientresource(1066) of type (stream)
Connection opend, total clients: 1
Received message:  {"user_id" : 123}
new clientresource(1069) of type (stream)
Connection opend, total clients: 1
Array
(
    [0] => WSSC\Components\Connection Object
        (
            [socketConnection:WSSC\Components\Connection:private] => Resource id #1066
        )

    [1] => WSSC\Components\Connection Object
        (
            [socketConnection:WSSC\Components\Connection:private] => Resource id #1069
        )

)
```
