### ISSUE TITLE
Not an Issue. Rather a question about an application

### ISSUE THREAD

**Issue by kapyaar** [arthurkushman/php-wss#66]
Hello,

I have a requirement where a bunch of sensors need to connect to a php server, and the server needs to make sure they are all connected. Currently I do a heartbeat http request from each sensor to the server to indicate it is alive. 

Is WSS a library that can be used to connect clients to a server, keep info on each connection in a database, and check every minute if each of the client connection (and thereby the sensor) is still open/ active?

Sorry if this is a noob question. Just looking for the best option to accomplish this. Any thoughts much appreciated.

**Comment by arthurkushman** [comment]
Hi, sure you can use a web-socket server as an subscriber/interrogator of a clients and also save the connection info (like unique socket ids etc), clients after they were connected should send some events, for example in your case it would be more relevant to send pings:
```php
    public function onPing(ConnectionContract $conn, $msg)
    {
        // TODO: Implement onPing() method.
    }
```

PS for discussions there is a better tool recently provided by GitHub - "Discussions"
