### ISSUE TITLE
How to install a socket server

### ISSUE THREAD

**Issue by it19862** [arthurkushman/php-wss#67]
I'm trying to install a server  
I use an OpenServer.  
Done.
 - downloaded the archive;  
 - placed files in a folder `C:\OpenServer\domains\phpWssArthurkushmanGithub`;
   
Now my folders look like in the picture.
   
**Question.**  
 1. How to use it? What should I add?  
 2. How to start the server?  
3. How to start the client?  

![27 05 2022_21-39-38](https://user-images.githubusercontent.com/18245828/170771063-ca688213-8aa9-4076-a4cd-bd0bc5426fb1.png)

**Comment by arthurkushman** [comment]
You need to create a file just like described in readme.md ex.:
```php
<?php
use WSSC\Contracts\ConnectionContract;
use WSSC\Contracts\WebSocket;
use WSSC\Exceptions\WebSocketException;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

class ServerHandler extends WebSocket
{

    /*
     *  if You need to parse URI context like /messanger/chat/JKN324jn4213
     *  You can do so by placing URI parts into an array - $pathParams, when Socket will receive a connection
     *  this variable will be appropriately set to key => value pairs, ex.: ':context' => 'chat'
     *  Otherwise leave $pathParams as an empty array
     */

    public $pathParams = [':entity', ':context', ':token'];
    private $clients = [];

    private $log;

    /**
     * ServerHandler constructor.
     *
     * @throws \Exception
     */
    public function __construct()
    {
        // create a log channel
        $this->log = new Logger('ServerSocket');
        $this->log->pushHandler(new StreamHandler('./tests/tests.log'));
    }

    public function onOpen(ConnectionContract $conn)
    {
        $this->clients[$conn->getUniqueSocketId()] = $conn;
        $this->log->debug('Connection opend, total clients: ' . count($this->clients));
    }

    public function onMessage(ConnectionContract $recv, $msg)
    {
        $this->log->debug('Received message:  ' . $msg);
        $recv->send($msg);
    }

    public function onClose(ConnectionContract $conn)
    {
        unset($this->clients[$conn->getUniqueSocketId()]);
        $this->log->debug('close: ' . print_r($this->clients, 1));
        $conn->close();
    }

    /**
     * @param ConnectionContract $conn
     * @param WebSocketException $ex
     */
    public function onError(ConnectionContract $conn, WebSocketException $ex)
    {
        echo 'Error occured: ' . $ex->printStack();
    }

    /**
     * You may want to implement these methods to bring ping/pong events
     *
     * @param ConnectionContract $conn
     * @param string $msg
     */
    public function onPing(ConnectionContract $conn, $msg)
    {
        // TODO: Implement onPing() method.
    }

    /**
     * @param ConnectionContract $conn
     * @param $msg
     * @return mixed
     */
    public function onPong(ConnectionContract $conn, $msg)
    {
        // TODO: Implement onPong() method.
    }
}
```

And run it with `php ServerHandler.php`, don't forget to install `php-wss` with command `composer require arthurkushman/php-wss`, the project itself shouldn't be just downloaded manually, because u need autoload and other features.

**Comment by it19862** [comment]
@arthurkushman 

I'm sorry I didn't understand you well...
I'll describe my problem in detail once again.
I use:
- Windows 10x64;
  - OpenSrver. https://ospanel.io / (analog of XAMPP);
  
I did:
- I downloaded the archive manually https://github.com/arthurkushman/php-wss;
	- I unpacked the archive;
	- in OpenSrver I created a folder: `phpWssArthurkushmanGithub2\` in the folder `c:\openserver\domains \`;
		Result: `c:\openserver\domains\phpWssArthurkushmanGithub2 \`;
	- I manually copied the `src` folder to the `c:\openserver\domains\phpWssArthurkushmanGithub2 \`;
			The folder contains `c:\openserver\domains\phpWssArthurkushmanGithub2\src\`
																		Components\
																		Contracts\
																		Exceptions\
																		WebSocketClient.php
																		WebSocketServer.php
	- I opened the OpenSrver console;
	- I entered the command: `cd c:\openserver\domains\phpWssArthurkushmanGithub2\`
	- I entered the command: `composer require arthurkushman/php-wss`
	- result: in the folder C:\OpenServer\domains\phpWssArthurkushmanGithub2 added folders and files
				src\
				vendor\
				composer.json
				composer.lock
				
**Questions.**
3. How to properly upload the `php-wss` project to your computer? 
2. Where to place the file `ServerHandler.php` ?
3. If you run the file ServerHandler.php will the server work in the browser?
4. How to create a client? Where to locate the client? How to launch the client?

![27 05 2022_23-12-51](https://user-images.githubusercontent.com/18245828/170784230-21b79d1d-cd8b-4b0b-a1a7-1b7b920ea365.png)
![27 05 2022_23-12-52](https://user-images.githubusercontent.com/18245828/170784232-8385f625-dc66-4739-ba97-3a9c281163ab.png)
![27 05 2022_23-12-56](https://user-images.githubusercontent.com/18245828/170784233-cf5f6d87-496d-4872-8b42-66e1ec987a87.png)
![27 05 2022_23-13-12](https://user-images.githubusercontent.com/18245828/170784235-fbdc6141-04ad-4d39-b73c-1c890c959033.png)
![27 05 2022_23-15-04](https://user-images.githubusercontent.com/18245828/170784238-d8ba6d6c-5e1f-4181-91d7-369ecee8d6d1.png)
![27 05 2022_23-16-05](https://user-images.githubusercontent.com/18245828/170784239-51ed1dd3-8fa2-42be-ae9f-e2eb40cb62a0.png)
![27 05 2022_23-16-23](https://user-images.githubusercontent.com/18245828/170784241-6b34ea09-2a00-459e-bb9f-35c84e48e144.png)

**Comment by arthurkushman** [comment]
Please create discussions here - https://github.com/arthurkushman/php-wss/discussions, as this is not an issue with php-wss lib at all, it seems more like your personal problems with installation. This library works for 7 years since 2015 in all OSs and large companies. So there are lots of misunderstanding of how to use php and it's libraries - nothing to do with php-wss.

Closing this issue due to irrelevant questions in context of an issue tracking.

PS I don't have time to explain to everybody how to install packages and use them on every system.
Hope for understanding.
