### ISSUE TITLE
Incorrectly closed connections

### ISSUE THREAD

**Issue by michalac** [arthurkushman/php-wss#7]
Hello,

Connection object incorrectly closes connection. There is missing reply to client after receiving event close (with opcode 8 - DECODE_CLOSE). Result is exception fired in client (for example JavaScript console) after closing websocket and incomplete closed sockets at server (visible in netstat with flag CLOSE_WAIT):

> s = new WebSocket("ws://nic.ehs.sk:8081/websocket/");
> s.close();
> Connection was interrupted while page is loading..

Solution is change Connection->close() method like this:
```
    public function close() : void
    {
        if (is_resource($this->socketConnection)) {
            // reply to close message
            fwrite($this->socketConnection, $this->encode('', self::EVENT_TYPE_CLOSE));
            fclose($this->socketConnection);
        }
    }

```
I'm new in Git/GutHub, and don't know to push patch to your project directly.

With regards
Michal

**Comment by arthurkushman** [comment]
This is not a good idea to send empty message on close event from the core, also there is no missing reply to the client after recv close, you can send whatever u need before close ex.:
```php
    public function onClose(ConnectionContract $conn)
    {
        $conn->send('whatever you need');
        unset($this->clients[array_search($conn, $this->clients)]);
        $conn->close();
    }
```
And then just perform some actions on client side if u'd like.
You can even do not close connection at all and run other processing if Your app logic needs it.

**Comment by michalac** [comment]
You must distinguish between 
a) sending a close command (frame with opcode 0x8) and 
b) closing the socket
Fist, client must send a close packet and wait to receive close command (frame with opcode 0x8) from server. After that, client closes the socket (sends TCP FIN).

Look at RFC6455 5.5.1:
>  If an endpoint receives a Close frame and did not previously send a Close frame, the **endpoint MUST send a Close frame in response**. 

It's on you, if you fix it or no. I inspired by your library (thank you), but I need to intense modify it for my specific needs.

**Comment by arthurkushman** [comment]
Again, sorry for delay - trying to fix all sequentially - u r definitely good at analysis of code, this is the second issue that helps this lib a lot.
