### ISSUE TITLE
"PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE"

### ISSUE THREAD

**Issue by jeankassio** [arthurkushman/php-wss#74]
`[29-Oct-2022 09:11:30 America/Sao_Paulo] PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1179.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in /home/admin/web/socket.nfxtrade.com/public_html/vendor/arthurkushman/php-wss/src/WebSocketServer.php on line 166`

From time to time this error is generated on my system and only corrects itself after restarting the server. All changes outside the code that I tried were insufficient to fix it

**Comment by arthurkushman** [comment]
Hi, thx for reporting on this php warning, the gist is in the line of C code here:
```C
#define __FD_SETSIZE
```
there is nothing to do with PHP, u need to recompile it with flags:
```zsh
./configure --enable-fd-setsize=10240 --enable-pcntl
```
more info here on this issue - https://bugs.php.net/bug.php?id=37025

**Comment by jeankassio** [comment]
Thank you, I will follow the recommendations and how can I proceed within my approval environment, I will take the opportunity to update PHP with this.
