### ISSUE TITLE
WscMain->send()

### ISSUE THREAD

**Issue by eugenchenko** [arthurkushman/php-wss#8]
line 179:        echo $payload;

Is it forgotten debug?

**Comment by arthurkushman** [comment]
Nice try, I suppose it is rather send to stdout (to see events in console), but defnitelly could be done better with some lib/helper method. It is not because everybody don’t know how to use xCode debugging tool )

**Comment by eugenchenko** [comment]
Few more:

ns3107210:~/vendor/arthurkushman/php-wss$ grep -R 'echo' *
src/WebSocketServer.php:                            echo 'trigger MESSAGE event';
src/Components/WscMain.php:        #echo $payload;
src/Exceptions/WebSocketException.php:        echo $this->getFile() . ' ' . $this->getLine() . ' ' . $this->getMessage() . PHP_EOL;
src/Exceptions/WebSocketException.php:        echo $this->getTraceAsString();
